branch-defaults:
  main:
    environment: my-app
    group_suffix: null
environment-defaults:
  my-app:
    branch: null
    repository: null
global:
  application_name: my-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
