# Generated by Django 3.2.7 on 2022-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자 여부')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
            },
        ),
    ]
